/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package day13

class App(input: String) {
    val patterns: List<Pattern> = input.split("\n\n").map { Pattern(it.split('\n')) }
    fun runStep1() = patterns.sumOf { it.getPerfectReflexionCount() }
}

fun main() {
    val app = App(puzzleInput)
    println("step 1: ${app.runStep1()}")
}
