/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package day13

data class Pattern(val lines: List<String>)

class App(input: String) {
    val patterns: List<Pattern>

    init {
        patterns = input.split("\n\n").map { Pattern(it.split('\n')) }
    }
}

fun main() {}
