/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package day13

import day13.*
import kotlin.test.Test

class AppTest {
    @Test
    fun appHasAGreeting() {
        val testApp = App(testInput)
    }
}
