/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package day7.kotlin

import kotlin.test.Test
import kotlin.test.assertEquals

class AppTest {
    @Test
    fun appRunsTestPart1() {
        val cardGame = CardGame.import(TEST_INPUT)
        assertEquals(6440, cardGame.run())
    }

    @Test
    fun appRunsTestPart2() {
        val cardGame = CardGame.import(TEST_INPUT, true)
        assertEquals(5905, cardGame.run())
    }
}
