/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package day7.kotlin

enum class HandType {
    FIVE_OF_A_KIND,
    FOUR_OF_A_KIND,
    FULL_HOUSE,
    THREE_OF_A_KIND,
    TWO_PAIR,
    ONE_PAIR,
    HIGH_CARD
}

data class Hand(val cards: List<Int>) : Comparable<Hand> {
    val type: HandType
        get() {
            val groups = this.cards.groupBy { it }
            return when (groups.count()) {
                1 -> HandType.FIVE_OF_A_KIND
                2 ->
                        if (groups.any { it.value.size == 4 }) HandType.FOUR_OF_A_KIND
                        else HandType.FULL_HOUSE
                3 ->
                        if (groups.any { it.value.size == 3 }) HandType.THREE_OF_A_KIND
                        else HandType.TWO_PAIR
                4 -> HandType.ONE_PAIR
                else -> HandType.HIGH_CARD
            }
        }

    override fun compareTo(other: Hand): Int {
        val comparison = compareTo(other)
        return if (comparison != 0) {
            comparison
        } else {
            val match = (this.cards zip other.cards).find { it.first != it.second }
            if (match != null) {
                return match.first.compareTo(match.second)
            }
            return 0
        }
    }
}

fun main() {}
